### ISSUE TITLE
Paper idea: national analysis of cycling uptake and exposure to cycling risk and street lighting

### ISSUE THREAD

**Issue by Robinlovelace** [saturnlighting/literature-review#1]
Dependent variable: km cycled per year per unit area (could be LA or 1 km grid cell or other).

Explanatory variables:

- Percentage of cycle network  (weighted by cycling levels on the network) that is unlit: total distance cycled / total distance cycled on segments that have the tag lit=no
- Percentage of cycle network (weighted by cycling levels on the network) that is not mixed with motor traffic
- ...

**Comment by eugenividal** [comment]
Closing this old issue.
