### ISSUE TITLE
to do list before submission

### ISSUE THREAD

**Issue by eugenividal** [saturnlighting/literature-review#13]
Hi @Robinlovelace, FYI this is a list of tasks to complete before the final submission: 
- [x] Reread all the paper for final touches (see how balanced and logical is the whole story from beginning to end)
- [x] Perhaps expand the abstract (I was wrong, it can be 300 words!)
- [x] Send a copy to Jim (I do not expect his feedback, but it could be very helpful. No need for his feedback before submission)
- [x] Include Funding details
- [x] Create high-quality images (1200 dpi for line art, 600 dpi for grayscale, and 300 dpi for colour -- Formats: EPS, PS, JPEG, TIFF)
- [x] Include zotero references in T&F standard APA style
- [x] Make list of potential reviewers

**Comment by Robinlovelace** [comment]
Great list Eugeni, fully agreed.

**Comment by eugenividal** [comment]
Heads-up @Robinlovelace, these are the funding details. How does it look?

# Acknowledgements

This work is part of the project Supporting Active Travel Using Road-lighting at Night (SATURN) funded by the Engineering and Physical Sciences Research Council (EPSRC) [grant number EP/V043463/1].

**Comment by eugenividal** [comment]
This is now complete!

**Comment by Robinlovelace** [comment]
:tada:
