### ISSUE TITLE
response-to-reviewers

### ISSUE THREAD

**Issue by eugenividal** [saturnlighting/literature-review#16]
Hi @Robinlovelace, I set up a 'response to reviewers' document here https://github.com/saturnlighting/literature-review/blob/main/revision1/response-to-reviewers/response-to-reviewers-revision1.Rmd, so we can both work on it at the same time. At the moment, I just included a short letter, the editor's and reviewers' comments, and your initial inputs. You can work on it when you are available. I will carry on working on it tomorrow. **The deadline is 3 Sep** but with a whole week's holiday in the middle.

**Comment by Robinlovelace** [comment]
Thanks Eugeni and noted re. deadline.

**Comment by Robinlovelace** [comment]
Update on this I've got the changes up and they look good so far. I'm happy to take next steps on this and should find time on tomorrow (Thursday 10th).

![image](https://github.com/saturnlighting/literature-review/assets/1825120/9e8f28e4-e813-4d9f-88af-2ce6d2010e59)

**Comment by eugenividal** [comment]
That's great, Robin! We can talk about this tomorrow in the ITS. I am working on the crime and lighting paper at the moment -- I'd like to send an update by the end of this week.
